spring:
  application:
    name: attendance
  datasource:
    url: jdbc:postgresql://localhost:5432/church_attendance
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    properties:
      
      hibernate:
        jdbc:
          time_zone: UTC 
        show_sql:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 3500

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
